@startuml

@startmindmap
* Counter 1: Asthotthara and Sankalpa
** Pooja Items
*** Small deepa / Neelanjana
*** Rayara Photo
*** Pachapaatre uddhrane
*** Mantrakshate baltu
** Setup Items
*** Table from hall
*** Fancy covering cloth
*** Leaf torana
** Human incharge
*** Archaka
*** Nidhi

* Counter 2: Kanakabhisheka and Paadapooja
** Pooja Items
*** Rayara Bronze Idol
*** Small deepa / Neelanjana
*** Halagarathi with tatte
*** Pachapaatre uddhrane
*** Mantrakshate baltu
*** Rayara Paaduka
*** Silver flowers
*** Rose petals
** Setup Items
*** Low table (XXLutz)
*** Fancy covering cloth
*** Leaf torana
*** Jamkhana (Koppala) / cloth table mat for devotees to sit
*** Nidhi


@endmindmap

@enduml
