@startmindmap
* Videos to be covered
** Previous day
*** 1. Prep videos (Timelapse and normal speed)
**** Stage setup
**** Vegetable chopping
**** Garland making
**** Kitchen prep
*** 2. Quiz for kids (Kinder betweener can conduct?)
**** On religious topic
** Event day
*** 1. Vishnu Sahasranaama
*** 2. Abhisheka (God + Brundavana)
**** Water, milk, fruits -> all 3 few secs
*** 3. Ashtottara
*** 4. Sangeetha Seva (Total no. of videos to be decided)
**** Min. 2
*** 5. Jnanasudha team chanting
**** Dwadasha Stotra, Pratah Sankalpa Gadya
**** Few secs each
*** 6. Harikathamrutha Saara chanting
*** 7. Kanakabhisheka (1 pooja video)
*** 8. Paada pooja (1 pooja video)
*** 9. Pravachana by Dr. Pratosh (few secs)
*** 10. Mahamangalaarathi
*** 11. Volunteer teams group wise Ashirvachana videos
*** 12. Dasara pada, quiz videos
**** At least 1 question and answer to be covered for each round
*** 13. Kitchen video (Cooking team video)
*** 14. Serving video (?)
*** 15. Feedback from devotees
@endmindmap
